name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! Thanks for your attention to detail, I will be sure to review this ASAP.'' first issue'
        pr-message: 'Hey! Thanks for the PR, it means a lot to have a helping hand on this project - I will review this ASAP and get back to you.'' first pr'
